pause(1)
disp("Comienza la grabación de la primera palabra")
voz("p1")
disp("Finaliza la grabación de la primera palabra")
pause(1)
disp("Comienza la grabación de la segunda palabra")
voz("p2")
disp("Finaliza la grabación de la segunda palabra")
pause(1)
disp("comienza la grabación de la tercera palabra")
voz("p3")
disp("Finaliza la grabación de la tercera palabra")
pause(1)
disp("Comienza la grabación de la cuarta palabra")
voz("p4")
disp("Finaliza la grabación de la cuarta palabra")